//
// Created by eceledon on 5/10/2022.
//

#ifndef EMPRESAVENTAMAS_PRODUCTOCONTROLLER_H
#define EMPRESAVENTAMAS_PRODUCTOCONTROLLER_H


class ProductoController {

};


#endif //EMPRESAVENTAMAS_PRODUCTOCONTROLLER_H
